export const SET_LOADING_ACTION = "SET_LOADING_ACTION"
export const SET_MESSAGE_ACTION = "SET_MESSAGE_ACTION"
export const SET_GOTO_URL_ACTION = "SET_GOTO_URL_ACTION"
export const SET_CURRENT_NAVIGATION_ITEM_ACTION = "SET_CURRENT_NAVIGATION_ITEM_ACTION"