# fly.toml app configuration file generated for mater-frontend on 2023-04-28T09:06:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mater-frontend"
primary_region = "dfw"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
